
services:
  argus-events:
    image: argus-events:latest  # Use existing image, don't build
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ARGUS_ENDPOINT=0.0.0.0:3000
      - ARGUS_REPOSITORY=memory
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/events"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - argus-events
    restart: unless-stopped
    profiles:
      - production
