name: CI

on:
  push:
    branches: [ main ]  # Only main branch pushes
  pull_request:
    branches: [ main ]  # All PRs to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test
        run: scripts/build.sh --color

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag argus-events:latest ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
